// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package source

import (
	"github.com/zhanghup/go-app/beans"
	"github.com/zhanghup/go-app/service/event"
)

type CronLogs struct {
	Total *int            `json:"total"`
	Data  []beans.CronLog `json:"data"`
}

type Crons struct {
	Total *int         `json:"total"`
	Data  []beans.Cron `json:"data"`
}

type Depts struct {
	Total *int         `json:"total"`
	Data  []beans.Dept `json:"data"`
}

type IPermObj struct {
	// 对象
	Object string `json:"object"`
	// 操作权限
	Mask string `json:"mask"`
}

type Message struct {
	Action  event.MsgAction `json:"action"`
	Message *beans.MsgInfo  `json:"message"`
}

type NewDept struct {
	// 组织类型{dict:BUS001}
	Type *string `json:"type"`
	// 组织代码
	Code *string `json:"code"`
	// 组织名称
	Name *string `json:"name"`
	// 组织头像
	Avatar *string `json:"avatar"`
	// 父级组织ID
	Pid *string `json:"pid"`
	// 备注
	Remark *string `json:"remark"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type NewDict struct {
	// 字典类型{dict:SYS001}
	Type *string `json:"type"`
	// 字典编码
	Code *string `json:"code"`
	// 字典名称
	Name *string `json:"name"`
	// 备注
	Remark *string `json:"remark"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type NewDictItem struct {
	// 字典id
	Code *string `json:"code"`
	// 名称
	Name *string `json:"name"`
	// 值
	Value *string `json:"value"`
	// 扩展
	Ext *string `json:"ext"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type NewMsgConfirm struct {
	// 确认备注
	Remark *string `json:"remark"`
}

type NewRole struct {
	// 角色描述
	Name *string `json:"name"`
	// 角色名称
	Desc *string `json:"desc"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type NewUser struct {
	// 用户类型{dict:BUS002}
	Type *string `json:"type"`
	// 用户名称
	Name *string `json:"name"`
	// 头像
	Avatar *string `json:"avatar"`
	// 身份证
	IDCard *string `json:"id_card"`
	// 出生年月
	Birth *int `json:"birth"`
	// 性别{dict:STA002}
	Sex *string `json:"sex"`
	// 移动电话
	Mobile *string `json:"mobile"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
	// 备注
	Remark *string `json:"remark"`
}

type PermObj struct {
	// 对象
	Object string `json:"object"`
	// 操作权限
	Mask string `json:"mask"`
}

type QCron struct {
	Keyword *string `json:"keyword"`
	Index   *int    `json:"index"`
	Size    *int    `json:"size"`
	Count   *bool   `json:"count"`
}

type QCronLog struct {
	Cron    string  `json:"cron"`
	Keyword *string `json:"keyword"`
	Index   *int    `json:"index"`
	Size    *int    `json:"size"`
	Count   *bool   `json:"count"`
}

type QDept struct {
	Pid   *string `json:"pid"`
	Index *int    `json:"index"`
	Size  *int    `json:"size"`
	Count *bool   `json:"count"`
}

type QDict struct {
	// 字典类型
	Type *string `json:"type"`
}

type QMsgTemplate struct {
	// 名称模糊查询
	Name *string `json:"name"`
	// 编码模糊查询
	Code *string `json:"code"`
}

type QRole struct {
	Keyword *string `json:"keyword"`
	Index   *int    `json:"index"`
	Size    *int    `json:"size"`
	Count   *bool   `json:"count"`
}

type QUser struct {
	Keyword *string `json:"keyword"`
	Index   *int    `json:"index"`
	Size    *int    `json:"size"`
	Count   *bool   `json:"count"`
}

type Roles struct {
	Total *int         `json:"total"`
	Data  []beans.Role `json:"data"`
}

type UpdDept struct {
	// 组织类型{dict:BUS001}
	Type *string `json:"type"`
	// 组织代码
	Code *string `json:"code"`
	// 组织名称
	Name *string `json:"name"`
	// 组织头像
	Avatar *string `json:"avatar"`
	// 父级组织ID
	Pid *string `json:"pid"`
	// 备注
	Remark *string `json:"remark"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type UpdDict struct {
	// 字典类型{dict:SYS001}
	Type *string `json:"type"`
	// 字典名称
	Name *string `json:"name"`
	// 备注
	Remark *string `json:"remark"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type UpdDictItem struct {
	// 名称
	Name *string `json:"name"`
	// 值
	Value *string `json:"value"`
	// 扩展
	Ext *string `json:"ext"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type UpdMsgTemplate struct {
	// 模板名称
	Name *string `json:"name"`
	// 消息分类{dict:SYS005}
	Type *string `json:"type"`
	// 消息等级{dict:SYS006}
	Level *string `json:"level"`
	// 消息推送平台{dict:SYS007}
	Target *string `json:"target"`
	// 消息超时时间（秒）
	Expire *int64 `json:"expire"`
	// 消息是否必须确认{dict:STA005}
	MustConfirm *string `json:"must_confirm"`
	// 消息提示图片
	ImgPath *string `json:"img_path"`
	// 备注
	Remark *string `json:"remark"`
}

type UpdRole struct {
	// 角色描述
	Name *string `json:"name"`
	// 角色名称
	Desc *string `json:"desc"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
}

type UpdUser struct {
	// 用户类型{dict:BUS002}
	Type *string `json:"type"`
	// 用户名称
	Name *string `json:"name"`
	// 头像
	Avatar *string `json:"avatar"`
	// 身份证
	IDCard *string `json:"id_card"`
	// 出生年月
	Birth *int `json:"birth"`
	// 性别{dict:STA002}
	Sex *string `json:"sex"`
	// 移动电话
	Mobile *string `json:"mobile"`
	// 排序
	Weight *int `json:"weight"`
	// 状态{dict:STA001}
	Status *string `json:"status"`
	// 备注
	Remark *string `json:"remark"`
}

type Users struct {
	Total *int         `json:"total"`
	Data  []beans.User `json:"data"`
}
